### ISSUE TITLE
getWeek() is broken

### ISSUE THREAD

**Issue by hmkrivoj** [corpsgeek/Date-Utility#1]
# Use an integer division (~/) instead of floating point division (/)
This function currently throws `type 'double' is not subtype of type 'int'` because it tries to store the result of an floating point division into an integer variable.

# Fix Unexpected Behavior
| Input | Expected | Actual |
| --- | --- | --- |
| 2021-1-1 | 53 | 1 |
| 2012-12-31 | 1 | 53 |

**Comment by jonjon1123** [comment]
I am also experiencing an issue with this. I have fixed the issue locally and tried to push a branch up to do a PR, but I don't have permissions. The fix is very simple. Just need to change the return type in this statement to: `double a = (daysPastInYear(monthNum, dayNum, year) / 7) + 1;`.

**Comment by jonjon1123** [comment]
I just filed a PR for this. Please approve and push a new version to dart pub.

**Comment by jakobmillah** [comment]
Still an issue. Any idea when this might get sorted?

**Comment by jonjon1123** [comment]
@jakobmillah The PR I filed is still waiting to be approved and merged by @corpsgeek
